sudo: required
dist: trusty
language: python
python:
  - 2.7
  - 3.5
git:
  submodules: true
before_install:
  - sudo add-apt-repository -y ppa:octave/stable
  - sudo apt-get update
  - sudo apt-get -y install curl octave liboctave-dev
  - octave --eval "pkg install -forge -verbose io"
  - octave --eval "pkg install -forge -verbose statistics"
install:
  - pip install pytest-cov coveralls
  - pip install -r requirements.txt
  - pip install -e .
script:
  - py.test --cov-config .coveragerc --cov-report term-missing --cov=kgp tests/
after_success:
  - coveralls
