# Templates for LSTM models

1H:
  input_shape: !!python/tuple {input_shape!r}
  output_shape: !!python/tuple {output_shape!r}
  hidden_layers:
  - name: LSTM
    config:
      name: H
      activation: {H_activation!r}
      return_sequences: False
      stateful: {stateful:b}
      units: {H_dim:d}
      dropout: {dropout_W:f}
      recurrent_dropout: {dropout_U:f}
    dropout: {dropout:f}
    batch_norm: {batch_norm!s}

2H:
  input_shape: !!python/tuple {input_shape!r}
  output_shape: !!python/tuple {output_shape!r}
  hidden_layers:
  - name: LSTM
    config:
      name: H1
      activation: {H_activation!r}
      return_sequences: True
      stateful: {stateful:b}
      units: {H_dim:d}
      dropout: {dropout_W:f}
      recurrent_dropout: {dropout_U:f}
    dropout: {dropout:f}
    batch_norm: {batch_norm!s}
  - name: LSTM
    config:
      name: H2
      activation: {H_activation!r}
      return_sequences: False
      stateful: {stateful:b}
      units: {H_dim:d}
      dropout: {dropout_W:f}
      recurrent_dropout: {dropout_U:f}
    dropout: {dropout:f}
    batch_norm: {batch_norm!s}
